name: 'WhichWrapper'
description: 'A wrapper action for the @actions/io which() function. Finds the path to a specified command and store as an output.'
inputs:
  command:
    description: 'The command to find on the runner.'
    required: true
  fail-on-not-found:
    description: 'Whether or not to fail the action if the command is not found. Defaults to false.'
    required: false
    default: false
outputs:
  path:
    description: 'The path to the specified command.'
runs:
  using: 'node20'
  main: 'index.js'
